config/routes.rb
Qichebaoyang::Application.routes.draw do
  resources :service_item_product_auto_model_ships

  resources :service_item_products

  resources :service_station_administrator_service_station_ships

  resources :service_station_administrators

  resources :customer_service_station_ships

  resources :maintenance_goods

  resources :car_maintenance_infos

  resources :customer_service_item_ships

  resources :customers

  resources :service_stations do
    resources :customers
  end

resources :service_items
resources :service_stations
  get 'service_station_lists', to: 'service_stations#service_station_lists'
  resources :user_administrations
  resources :user_records

  devise_for :users

  resources :users do
    resource :user_records
  end

  resources :auto_models
  resources :auto_maintenances
  resources :auto_brands

  get 'user_record/update_auto_models' => 'user_records#update_auto_models'
  get 'm' => 'user_records#m_new'
  get 'service_item/update_auto_models' => 'service_items#update_auto_models'

  root 'user_records#new'

  

end

app/models/service_item_product_auto_model_ship.rb
class ServiceItemProductAutoModelShip < ActiveRecord::Base
  belongs_to :service_item_product
  belongs_to :auto_model
end

app/controllers/service_item_product_auto_model_ships_controller.rb
class ServiceItemProductAutoModelShipsController < ApplicationController
  before_action :set_service_item_product_auto_model_ship, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @service_item_product_auto_model_ships = ServiceItemProductAutoModelShip.all
    respond_with(@service_item_product_auto_model_ships)
  end

  def show
    respond_with(@service_item_product_auto_model_ship)
  end

  def new
    @service_item_product_auto_model_ship = ServiceItemProductAutoModelShip.new
    respond_with(@service_item_product_auto_model_ship)
  end

  def edit
  end

  def create
    @service_item_product_auto_model_ship = ServiceItemProductAutoModelShip.new(service_item_product_auto_model_ship_params)
    @service_item_product_auto_model_ship.save
    respond_with(@service_item_product_auto_model_ship)
  end

  def update
    @service_item_product_auto_model_ship.update(service_item_product_auto_model_ship_params)
    respond_with(@service_item_product_auto_model_ship)
  end

  def destroy
    @service_item_product_auto_model_ship.destroy
    respond_with(@service_item_product_auto_model_ship)
  end

  private
    def set_service_item_product_auto_model_ship
      @service_item_product_auto_model_ship = ServiceItemProductAutoModelShip.find(params[:id])
    end

    def service_item_product_auto_model_ship_params
      params.require(:service_item_product_auto_model_ship).permit(:service_item_product_id, :auto_model_id)
    end
end

app/helpers/service_item_product_auto_model_ships_helper.rb
module ServiceItemProductAutoModelShipsHelper
end

app/views/service_item_product_auto_model_ships/_form.html.erb
<%= form_for(@service_item_product_auto_model_ship) do |f| %>
  <% if @service_item_product_auto_model_ship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service_item_product_auto_model_ship.errors.count, "error") %> prohibited this service_item_product_auto_model_ship from being saved:</h2>

      <ul>
      <% @service_item_product_auto_model_ship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :service_item_product_id %><br>
    <%= f.number_field :service_item_product_id %>
  </div>
  <div class="field">
    <%= f.label :auto_model_id %><br>
    <%= f.number_field :auto_model_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/service_item_product_auto_model_ships/edit.html.erb
<h1><%= t("edit_service_item_product") %></h1>

<%= render 'form' %>

<%= link_to 'Show', @service_item_product_auto_model_ship %> |
<%= link_to 'Back', service_item_product_auto_model_ships_path %>

app/views/service_item_product_auto_model_ships/index.html.erb
<h1>Listing service_item_product_auto_model_ships</h1>

<table>
  <thead>
    <tr>
      <th>Service item product</th>
      <th>Auto model</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @service_item_product_auto_model_ships.each do |service_item_product_auto_model_ship| %>
      <tr>
        <td><%= service_item_product_auto_model_ship.service_item_product_id %></td>
        <td><%= service_item_product_auto_model_ship.auto_model_id %></td>
        <td><%= link_to 'Show', service_item_product_auto_model_ship %></td>
        <td><%= link_to 'Edit', edit_service_item_product_auto_model_ship_path(service_item_product_auto_model_ship) %></td>
        <td><%= link_to 'Destroy', service_item_product_auto_model_ship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service item product auto model ship', new_service_item_product_auto_model_ship_path %>

app/views/service_item_product_auto_model_ships/new.html.erb
<h1>New service_item_product_auto_model_ship</h1>

<%= render 'form' %>

<%= link_to 'Back', service_item_product_auto_model_ships_path %>

app/views/service_item_product_auto_model_ships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Service item product:</strong>
  <%= @service_item_product_auto_model_ship.service_item_product_id %>
</p>

<p>
  <strong>Auto model:</strong>
  <%= @service_item_product_auto_model_ship.auto_model_id %>
</p>

<%= link_to 'Edit', edit_service_item_product_auto_model_ship_path(@service_item_product_auto_model_ship) %> |
<%= link_to 'Back', service_item_product_auto_model_ships_path %>