config/routes.rb
Qichebaoyang::Application.routes.draw do
  resources :service_item_product_auto_model_ships

  resources :service_item_products

  resources :service_station_administrator_service_station_ships

  resources :service_station_administrators

  resources :customer_service_station_ships

  resources :maintenance_goods

  resources :car_maintenance_infos

  resources :customer_service_item_ships

  resources :customers

  resources :service_stations do
    resources :customers
  end

resources :service_items
resources :service_stations
  get 'service_station_lists', to: 'service_stations#service_station_lists'
  resources :user_administrations
  resources :user_records

  devise_for :users

  resources :users do
    resource :user_records
  end

  resources :auto_models
  resources :auto_maintenances
  resources :auto_brands

  get 'user_record/update_auto_models' => 'user_records#update_auto_models'
  get 'm' => 'user_records#m_new'
  get 'service_item/update_auto_models' => 'service_items#update_auto_models'

  root 'user_records#new'

  

end

app/models/customer_service_station_ship.rb
class CustomerServiceStationShip < ActiveRecord::Base
  belongs_to :customer
  belongs_to :service_station
end

app/controllers/customer_service_station_ships_controller.rb
class CustomerServiceStationShipsController < ApplicationController
  before_action :set_customer_service_station_ship, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @customer_service_station_ships = CustomerServiceStationShip.all
    respond_with(@customer_service_station_ships)
  end

  def show
    respond_with(@customer_service_station_ship)
  end

  def new
    @customer_service_station_ship = CustomerServiceStationShip.new
    respond_with(@customer_service_station_ship)
  end

  def edit
  end

  def create
    @customer_service_station_ship = CustomerServiceStationShip.new(customer_service_station_ship_params)
    @customer_service_station_ship.save
    respond_with(@customer_service_station_ship)
  end

  def update
    @customer_service_station_ship.update(customer_service_station_ship_params)
    respond_with(@customer_service_station_ship)
  end

  def destroy
    @customer_service_station_ship.destroy
    respond_with(@customer_service_station_ship)
  end

  private
    def set_customer_service_station_ship
      @customer_service_station_ship = CustomerServiceStationShip.find(params[:id])
    end

    def customer_service_station_ship_params
      params.require(:customer_service_station_ship).permit(:customer_id, :service_station_id)
    end
end

app/helpers/customer_service_station_ships_helper.rb
module CustomerServiceStationShipsHelper
end

app/views/customer_service_station_ships/_form.html.erb
<%= form_for(@customer_service_station_ship) do |f| %>
  <% if @customer_service_station_ship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer_service_station_ship.errors.count, "error") %> prohibited this customer_service_station_ship from being saved:</h2>

      <ul>
      <% @customer_service_station_ship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.number_field :customer_id %>
  </div>
  <div class="field">
    <%= f.label :service_station_id %><br>
    <%= f.number_field :service_station_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customer_service_station_ships/edit.html.erb
<h1>Editing customer_service_station_ship</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer_service_station_ship %> |
<%= link_to 'Back', customer_service_station_ships_path %>

app/views/customer_service_station_ships/index.html.erb
<h1>Listing customer_service_station_ships</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Service station</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customer_service_station_ships.each do |customer_service_station_ship| %>
      <tr>
        <td><%= customer_service_station_ship.customer_id %></td>
        <td><%= customer_service_station_ship.service_station_id %></td>
        <td><%= link_to 'Show', customer_service_station_ship %></td>
        <td><%= link_to 'Edit', edit_customer_service_station_ship_path(customer_service_station_ship) %></td>
        <td><%= link_to 'Destroy', customer_service_station_ship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer service station ship', new_customer_service_station_ship_path %>

app/views/customer_service_station_ships/new.html.erb
<h1>New customer_service_station_ship</h1>

<%= render 'form' %>

<%= link_to 'Back', customer_service_station_ships_path %>

app/views/customer_service_station_ships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @customer_service_station_ship.customer_id %>
</p>

<p>
  <strong>Service station:</strong>
  <%= @customer_service_station_ship.service_station_id %>
</p>

<%= link_to 'Edit', edit_customer_service_station_ship_path(@customer_service_station_ship) %> |
<%= link_to 'Back', customer_service_station_ships_path %>