config/routes.rb
Qichebaoyang::Application.routes.draw do
  resources :service_item_product_auto_model_ships

  resources :service_item_products

  resources :service_station_administrator_service_station_ships

  resources :service_station_administrators

  resources :customer_service_station_ships

  resources :maintenance_goods

  resources :car_maintenance_infos

  resources :customer_service_item_ships

  resources :customers

  resources :service_stations do
    resources :customers
  end

resources :service_items
resources :service_stations
  get 'service_station_lists', to: 'service_stations#service_station_lists'
  resources :user_administrations
  resources :user_records

  devise_for :users

  resources :users do
    resource :user_records
  end

  resources :auto_models
  resources :auto_maintenances
  resources :auto_brands

  get 'user_record/update_auto_models' => 'user_records#update_auto_models'
  get 'm' => 'user_records#m_new'
  get 'service_item/update_auto_models' => 'service_items#update_auto_models'

  root 'user_records#new'

  

end

app/models/service_item.rb
class ServiceItem < ActiveRecord::Base
  belongs_to :auto_model
  has_one :customer_service_item_ship
  def auto_brand_id
    @auto_brands = AutoBrand.all
  end
end

app/controllers/service_items_controller.rb
class ServiceItemsController < ApplicationController
  before_action :set_service_item, only: [:show, :edit, :update, :destroy]

  # GET /service_items
  # GET /service_items.json
  def index
    @service_items = ServiceItem.all
  end

  def update_auto_models
    @auto_models = AutoModel.where(auto_brand_id: params[:auto_brand_id])
  end

  # GET /service_items/1
  # GET /service_items/1.json
  def show
  end

  # GET /service_items/new
  def new
    @service_item = ServiceItem.new
  end

  # GET /service_items/1/edit
  def edit
  end

  # POST /service_items
  # POST /service_items.json
  def create
    @service_item = ServiceItem.new(service_item_params)

    respond_to do |format|
      if @service_item.save
        format.html { redirect_to @service_item, notice: 'Service item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @service_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @service_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_items/1
  # PATCH/PUT /service_items/1.json
  def update
    respond_to do |format|
      if @service_item.update(service_item_params)
        format.html { redirect_to @service_item, notice: 'Service item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @service_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_items/1
  # DELETE /service_items/1.json
  def destroy
    @service_item.destroy
    respond_to do |format|
      format.html { redirect_to service_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_item
      @service_item = ServiceItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_item_params
      params.require(:service_item).permit(:name, :duration1, :duration2, :mile, :auto_model_id, :step)
    end
end

app/helpers/service_items_helper.rb
module ServiceItemsHelper
  def auto_brand_options
    AutoBrand.all.collect { |brand| [brand.name, brand.id] }
  end
end

app/views/service_items/_form.html.erb
<%= form_for(@service_item) do |f| %>
  <% if @service_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service_item.errors.count, "error") %> prohibited this service_item from being saved:</h2>

      <ul>
      <% @service_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :duration1 %><br>
    <%= f.number_field :duration1 %>
  </div>
  <div class="field">
    <%= f.label :duration2 %><br>
    <%= f.number_field :duration2 %>
  </div>
  <div class="field">
    <%= f.label :mile %><br>
    <%= f.number_field :mile %>
  </div>
  <div class="field">
    <%= f.label :step %><br>
    <%= f.number_field :step %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/service_items/edit.html.erb
<section id="content">
  <div class="container">
    <h1><%= t("edit_service_item") %></h1>

    <%= render 'form' %>

    <%= link_to 'Show', @service_item %> |
    <%= link_to 'Back', service_items_path %>
  </div>
</section>

app/views/service_items/index.html.erb
<h1><%= t("list_service_item") %></h1>

<section id="content">
  <div class="container">
    <table>
      <thead>
        <tr>
          <th><%= t("activerecord.attributes.service_item.name") %></th>
          <th><%= t("activerecord.attributes.service_item.duration1") %></th>
          <th><%= t("activerecord.attributes.service_item.duration2") %></th>
          <th><%= t("activerecord.attributes.service_item.mile") %></th>
          <td><%= t("activerecord.attributes.service_item.step") %></td>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @service_items.each do |service_item| %>
          <tr>
            <td><%= service_item.name %></td>
            <td><%= service_item.duration1 %></td>
            <td><%= service_item.duration2 %></td>
            <td><%= service_item.mile %></td>
            <td><%= service_item.step %></td>
            <td><%= link_to 'Show', service_item %></td>
            <td><%= link_to 'Edit', edit_service_item_path(service_item) %></td>
            <td><%= link_to 'Destroy', service_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</section>

<%= link_to t("new_service_item"), new_service_item_path %>

app/views/service_items/new.html.erb
<section id="content">
  <div class="container">
    <h1><%= t("new_service_item") %></h1>

    <%= render 'form' %>

    <%= link_to 'Back', service_items_path %>
  </div>
</section>

app/views/service_items/show.html.erb
<p id="notice"><%= notice %></p>
<section id="content">
  <div class="container">

    <p>
      <strong><%= t("activerecord.attributes.service_item.name") %></strong>
      <%= @service_item.name %>
    </p>

    <p>
      <strong><%= t("activerecord.attributes.service_item.duration1") %></strong>
      <%= @service_item.duration1 %>
    </p>

    <p>
      <strong><%= t("activerecord.attributes.service_item.duration2") %></strong>
      <%= @service_item.duration2 %>
    </p>

    <p>
      <strong><%= t("activerecord.attributes.service_item.mile") %></strong>
      <%= @service_item.mile %>
    </p>

    <p>
      <strong><%= t("activerecord.attributes.service_item.step") %></strong>
      <%= @service_item.step %>
    </p>

    <%= link_to 'Edit', edit_service_item_path(@service_item) %> |
    <%= link_to 'Back', service_items_path %>

  </div>
</section>

app/views/service_items/update_auto_models.js.erb
/**
 * Created by spmno on 2014/10/16.
 */
$('#service_item_auto_model_id').html("<%= escape_javascript options_from_collection_for_select(@auto_models, :id, :name) %>");
$('#service_item_auto_model_id').addClass('form-control');