config/routes.rb
Qichebaoyang::Application.routes.draw do
  resources :service_item_product_auto_model_ships

  resources :service_item_products

  resources :service_station_administrator_service_station_ships

  resources :service_station_administrators

  resources :customer_service_station_ships

  resources :maintenance_goods

  resources :car_maintenance_infos

  resources :customer_service_item_ships

  resources :customers

  resources :service_stations do
    resources :customers
  end

resources :service_items
resources :service_stations
  get 'service_station_lists', to: 'service_stations#service_station_lists'
  resources :user_administrations
  resources :user_records

  devise_for :users

  resources :users do
    resource :user_records
  end

  resources :auto_models
  resources :auto_maintenances
  resources :auto_brands

  get 'user_record/update_auto_models' => 'user_records#update_auto_models'
  get 'm' => 'user_records#m_new'
  get 'service_item/update_auto_models' => 'service_items#update_auto_models'

  root 'user_records#new'

  

end

app/models/car_maintenance_info.rb
class CarMaintenanceInfo < ActiveRecord::Base
  paginates_per 10
end

app/controllers/car_maintenance_infos_controller.rb
class CarMaintenanceInfosController < ApplicationController
  before_action :set_car_maintenance_info, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @car_maintenance_infos = CarMaintenanceInfo.page(params[:page])
    respond_with(@car_maintenance_infos)
  end

  def show
    respond_with(@car_maintenance_info)
  end

  def new
    @car_maintenance_info = CarMaintenanceInfo.new
    respond_with(@car_maintenance_info)
  end

  def edit
  end

  def create
    @car_maintenance_info = CarMaintenanceInfo.new(car_maintenance_info_params)
    @car_maintenance_info.save
    respond_with(@car_maintenance_info)
  end

  def update
    @car_maintenance_info.update(car_maintenance_info_params)
    respond_with(@car_maintenance_info)
  end

  def destroy
    @car_maintenance_info.destroy
    respond_with(@car_maintenance_info)
  end

  private
    def set_car_maintenance_info
      @car_maintenance_info = CarMaintenanceInfo.find(params[:id])
    end

    def car_maintenance_info_params
      params.require(:car_maintenance_info).permit(:title, :content)
    end
end

app/helpers/car_maintenance_infos_helper.rb
module CarMaintenanceInfosHelper
end

app/views/car_maintenance_infos/_form.html.erb
<%= form_for(@car_maintenance_info) do |f| %>
  <% if @car_maintenance_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car_maintenance_info.errors.count, "error") %> prohibited this car_maintenance_info from being saved:</h2>

      <ul>
      <% @car_maintenance_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class:"col-md-8" %>
  </div>
    <div class="clearfix"> </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, class:"col-md-8" %>
  </div>
    <div class="clearfix"> </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/car_maintenance_infos/edit.html.erb
<h1>Editing car_maintenance_info</h1>

<%= render 'form' %>

<%= link_to 'Show', @car_maintenance_info %> |
<%= link_to 'Back', car_maintenance_infos_path %>

app/views/car_maintenance_infos/index.html.erb
<h1><%= t("list_car_maintenance_info") %></h1>


<section id="content">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <article>
          <% @car_maintenance_infos.each do |car_maintenance_info| %>
            <div class="post-heading">
              <h3><%= car_maintenance_info.title %></h3>
            </div>
            <p>
              <%= car_maintenance_info.content %>
            </p>

            <div class="bottom-article">
              <%= link_to 'Show', car_maintenance_info %>
              <%= link_to 'Edit', edit_car_maintenance_info_path(car_maintenance_info) %>
              <%= link_to 'Destroy', car_maintenance_info, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          <% end %>
        </article>
      </div>
    </div>
  </div>
</section>
<br>

<%= link_to t("new_car_maintenances_info"), new_car_maintenance_info_path %>
<%= paginate @car_maintenance_infos %>

app/views/car_maintenance_infos/new.html.erb
<section id="content">
  <div class="container">
    <h1><%= t("new_car_maintenances_info") %></h1>
    <%= render 'form' %>
  </div>

</section>
<%= link_to 'Back', car_maintenance_infos_path %>

app/views/car_maintenance_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @car_maintenance_info.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @car_maintenance_info.content %>
</p>

<%= link_to 'Edit', edit_car_maintenance_info_path(@car_maintenance_info) %> |
<%= link_to 'Back', car_maintenance_infos_path %>